name: datos_DEEP
dependencies:
- pip
- python
- pip
- ipython
- jupyter
- matplotlib
- numpy
- pandas
- seaborn
- colorama
- termcolor
- langdetect
- holoviews
- bokeh
- scipy
- openpyxl
- sympy
- pip:
  - filterpy
